/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peertutormangament;

import java.awt.*;
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Helia
 */
public class BookSearchFrame extends javax.swing.JFrame {

    DefaultTableModel table;
    BookFrame bookFrame;
    public String codeInput;//grab the input course code
    boolean empty;//used to check if the textfield is empty or not

    /**
     * Creates new form BookSearchFrame
     */
    public BookSearchFrame() {
        initComponents();
        bookFrame = new BookFrame();
        empty = true;
        table = (DefaultTableModel) bookFrame.bookingTable.getModel();//grab the model of the jTable in bookframe
        setTitle("Search for a tutor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseTF = new javax.swing.JTextField();
        searchB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseTF.setForeground(new java.awt.Color(153, 153, 153));
        courseTF.setText("Enter code");
        courseTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                courseTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                courseTFFocusLost(evt);
            }
        });
        courseTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTFActionPerformed(evt);
            }
        });
        getContentPane().add(courseTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 289, 278, 44));

        searchB.setText("Search");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });
        getContentPane().add(searchB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 363, -1, -1));

        backB.setForeground(new java.awt.Color(60, 63, 65));
        backB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peertutormangament/back.png"))); // NOI18N
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        label1.setText("SEARCH FOR A TUTOR");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 490, 80));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        label2.setText("Format example: ICS4U1");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peertutormangament/background.png"))); // NOI18N
        jLabel1.setText("Format example: ICS4U1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTFActionPerformed
    }//GEN-LAST:event_courseTFActionPerformed

    public void Music(String location) {//play music from the given path when called
        InputStream music;
        try {
            music = new FileInputStream(new File(location));//find the music file
            AudioStream audio = new AudioStream(music);
            AudioPlayer.player.start(audio);//play the music right away
        } catch (IOException e) {
        }
    }
    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        UIManager UI = new UIManager();
        UI.put("OptionPane.background", Color.blue);
        codeInput = (courseTF.getText()).toUpperCase();//turn every input to uppercase for easier search
        File tutorCSV = new File ("tutor.csv");
        if (empty == true || codeInput.length() != 6) {//if the course code textfield is empty or not the length of a regular course code, show an error message
            UIManager.put("OptionPane.background", new Color (0,120,235));//change the background of the option pane
            Music("error.wav");
            String msg = "Please enter a valid course code";
            JOptionPane.showMessageDialog(null, msg, "Blue Screen of Death", JOptionPane.INFORMATION_MESSAGE);
        } else {//look through the list and find tutors who are offering help for the inputted course code
            Scanner s = null;
            try {
                s = new Scanner(tutorCSV);
            } catch (FileNotFoundException e) {
                UIManager.put("OptionPane.background", new Color (0,120,235));
                JOptionPane.showMessageDialog(null, "Error 404: File not found");//because I can
            }
            /*
            This section of the code goes through the list of tutors in the csv file. If it finds a tutor who is offer help in a given course code, 
            it will add their details to the table in BookFrame
             */
            String user = s.nextLine();// skip the column headers
            while (s.hasNextLine()) { //go through every tutor
                try {
                    user = s.nextLine();
                    String[] fields = user.split(",");//separate the details into fields array
                    boolean booked = Boolean.parseBoolean(fields[8]);
                    if ((fields[4].equals(codeInput) || fields[5].equals(codeInput) || fields[6].equals(codeInput)) && booked == false) { //tutor must not be booked and must teach the searched course
                        table.addRow(new Object[]{fields[2], fields[3], fields[9], fields[4], fields[5], fields[6]});//add the details to the table
                    }
                } catch (NoSuchElementException e) {//break from for loop when reached the end of the list
                    break;
                } catch (NullPointerException ex) {//in case there's missing info in the application
                }
            }
            if (table.getRowCount() <= 0) {//if no tutors found, throw an error message to user
                Music("error.wav");
                UIManager.put("OptionPane.background", new Color (0,120,235));
                JOptionPane.showMessageDialog(null, "No tutors found");
            } else {//if a tutor is found, show the table
                dispose();//close the book search frame window
                bookFrame.setResult("Showing results for: " + codeInput);
                bookFrame.setCode(codeInput);//pass the user input to the bookFrame 
                bookFrame.setVisible(true);//open up the book window
            }
        }
    }//GEN-LAST:event_searchBActionPerformed

    private void courseTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_courseTFFocusGained
        if (courseTF.getText().equals("Enter code")) {
            empty = false;
            courseTF.setText("");
            courseTF.setForeground(new Color(0, 0, 0));//change the colour to black when the user is typing 
        }
    }//GEN-LAST:event_courseTFFocusGained

    private void courseTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_courseTFFocusLost
        if (courseTF.getText().equals("")) {// a place holder for the user to put in a code
            empty = true;
            courseTF.setText("Enter code");
            courseTF.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_courseTFFocusLost

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        dispose();//close the window
        StudentWelcomeFrame welcome = null;
        try {
            welcome = new StudentWelcomeFrame();//open up the welcome page
        } catch (FileNotFoundException ex) {
        }
        welcome.welcomeLabel.setText("Did you book anyone?");
        welcome.setVisible(true);
    }//GEN-LAST:event_backBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JTextField courseTF;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JButton searchB;
    // End of variables declaration//GEN-END:variables
}
