/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peertutormangament;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.*;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author claire
 */
public class LoginPanel extends javax.swing.JPanel {
    // init variables
    File info = new File("tutees.csv");
    ArrayList<TuteeInfo> tutees = new ArrayList<>();
    String delim = ",";
    Image bg;
    // grab values from fields
    String givenUser = "", givenPw = "", adPw = "", adUser = "";
    
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        bg = Toolkit.getDefaultToolkit().getImage("background.png");//image import
    }
    @Override
    public void paintComponent (Graphics g){
        super.paintComponent(g);
        g.drawImage(bg, 0, 0, this); //draw the background image starting at 0,0
        g.setColor(Color.white);
        g.fillRect(130, 170, 185, 210);//student login block
        g.fillRect(480, 170, 185, 210);//admin login block
        g.fillRect(100, 30, 600, 75);//welcome message block
        g.fillRect(330, 115, 130, 60);//login message block
        repaint();
    }
    /**
     * Reads in all tutees from csv file
     * @throws FileNotFoundException 
     */
    public void read() throws FileNotFoundException {
        // initializing variables
        Scanner sc = new Scanner(info);
        String[] list;
        // reading the file to get tutee info
        while (sc.hasNextLine()) {
            // splitting info for easy access
            String fields = sc.nextLine();
            list = fields.split(delim);
            // adding tutees
            TuteeInfo t = new TuteeInfo(list[2], list[3], list[4]);
            tutees.add(t);
        }
    }
    /**
     * Checks if tutee exists in system
     * @return 
     */
    public int exist() {
        // looping through arraylist of tutees
        for (int i = 0; i < tutees.size(); i++) {
            // checking usernames in file and fields
            if (((tutees.get(i)).studentNo).equals(givenUser)) {
                return i;
            }
        }
        return -1;
    }
    /**
     * Checks for the right password 
     * @return whether the entered credentials are valid
     */ 
    public boolean valid() {
        // getting index of tutee
        if (exist() != -1) {
            // checking passwords in file and fields
            if (tutees.get(exist()).password.equals(givenPw)) {
                return true;
            }
        }
        return false;
    }
    /**
     * Hard-coded admin credentials 
     * user: a
     * pw: admin
     * @return validity of credentials
     */
    public boolean isAdmin() {
        return adPw.equals("admin") && adUser.equals("a");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
