/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peertutormangament;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author claire
 */
public class LoginFrame extends javax.swing.JFrame {
    // init class variables for navigation
    StudentWelcomeFrame studentWelcomeFrame;
    AdminSearchFrame adminSearchFrame;
    TuteeInfo tutee; // variable to transfer tutee identity to welcome frame
    /**
     * Creates new form LoginFrame
     * @throws java.io.FileNotFoundException
     */
    public LoginFrame() throws FileNotFoundException {
        initComponents();
        setTitle("Login");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        loginPanel1 = new peertutormangament.LoginPanel();
        loginLabel = new javax.swing.JLabel();
        studentLoginLabel = new javax.swing.JLabel();
        adminLoginLabel = new javax.swing.JLabel();
        userStudentLoginLabel = new javax.swing.JLabel();
        userStudentLoginField = new javax.swing.JTextField();
        pwStudentLoginLabel = new javax.swing.JLabel();
        pwStudentLoginField = new javax.swing.JTextField();
        studentLoginButton = new javax.swing.JButton();
        userAdminLoginLabel = new javax.swing.JLabel();
        userAdminLoginField = new javax.swing.JTextField();
        pwAdminLoginLabel = new javax.swing.JLabel();
        pwAdminLoginField = new javax.swing.JTextField();
        adminLoginButton = new javax.swing.JButton();
        loginTitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel1.setPreferredSize(new java.awt.Dimension(575, 362));

        loginLabel.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        loginLabel.setText("Login");

        studentLoginLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        studentLoginLabel.setText("Student");

        adminLoginLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        adminLoginLabel.setText("Admin");

        userStudentLoginLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userStudentLoginLabel.setText("Username:");

        userStudentLoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userStudentLoginFieldActionPerformed(evt);
            }
        });

        pwStudentLoginLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwStudentLoginLabel.setText("Password:");

        pwStudentLoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwStudentLoginFieldActionPerformed(evt);
            }
        });

        studentLoginButton.setText("Login");
        studentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLoginButtonActionPerformed(evt);
            }
        });

        userAdminLoginLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userAdminLoginLabel.setText("Username:");

        userAdminLoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAdminLoginFieldActionPerformed(evt);
            }
        });

        pwAdminLoginLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwAdminLoginLabel.setText("Password:");

        pwAdminLoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwAdminLoginFieldActionPerformed(evt);
            }
        });

        adminLoginButton.setText("Login");
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });

        loginTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginTitleLabel.setText("Welcome to the Peer Tutoring Management System!");

        javax.swing.GroupLayout loginPanel1Layout = new javax.swing.GroupLayout(loginPanel1);
        loginPanel1.setLayout(loginPanel1Layout);
        loginPanel1Layout.setHorizontalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(studentLoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminLoginLabel)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel1Layout.createSequentialGroup()
                        .addComponent(loginTitleLabel)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel1Layout.createSequentialGroup()
                        .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pwStudentLoginLabel)
                            .addComponent(userStudentLoginLabel))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userStudentLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwStudentLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanel1Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(userAdminLoginLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel1Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(pwAdminLoginLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwAdminLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userAdminLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(studentLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(loginLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanel1Layout.setVerticalGroup(
            loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(loginTitleLabel)
                .addGap(28, 28, 28)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentLoginLabel)
                    .addComponent(adminLoginLabel))
                .addGap(23, 23, 23)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userStudentLoginField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userAdminLoginLabel)
                        .addComponent(userAdminLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userStudentLoginLabel)))
                .addGap(18, 18, 18)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwStudentLoginLabel)
                        .addComponent(pwStudentLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwAdminLoginLabel)
                        .addComponent(pwAdminLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(loginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminLoginButton)
                    .addComponent(studentLoginButton))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userStudentLoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userStudentLoginFieldActionPerformed
            
    }//GEN-LAST:event_userStudentLoginFieldActionPerformed

    private void pwStudentLoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwStudentLoginFieldActionPerformed
         
    }//GEN-LAST:event_pwStudentLoginFieldActionPerformed

    private void pwAdminLoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwAdminLoginFieldActionPerformed
           
    }//GEN-LAST:event_pwAdminLoginFieldActionPerformed

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        // init variables
        loginPanel1.adPw = pwAdminLoginField.getText();
        loginPanel1.adUser = userAdminLoginField.getText();
        
        if (loginPanel1.isAdmin()) {
            // navigate to admin welcome page, close login
            adminSearchFrame = new AdminSearchFrame();
            setVisible(false);
            adminSearchFrame.setVisible(true);
        } else {
            // display error message
            String msg = "Incorrect credentials";
            JOptionPane.showMessageDialog(null, msg);
            // clearing fields
            userAdminLoginField.setText(null);
            pwAdminLoginField.setText(null);
        }
    }//GEN-LAST:event_adminLoginButtonActionPerformed

    private void userAdminLoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAdminLoginFieldActionPerformed
           
    }//GEN-LAST:event_userAdminLoginFieldActionPerformed

    private void studentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLoginButtonActionPerformed
        // TODO add your handling code here:
        // initializing variables
        loginPanel1.givenUser = userStudentLoginField.getText();
        loginPanel1.givenPw = pwStudentLoginField.getText();
        try {
            // reading the file before comparison
            loginPanel1.read();
        } catch (FileNotFoundException ex) {
            // error message
            String msg = "Error - needed files are missing";
            JOptionPane.showMessageDialog(null, msg);
        }
        if (loginPanel1.exist() == -1) {
            // display error message - this user does not exist
            String msg = "This user does not exist";
            JOptionPane.showMessageDialog(null, msg);
            // clearing text fields
            userStudentLoginField.setText(null);
            pwStudentLoginField.setText(null);
        } else if (loginPanel1.valid() == false) {
            // display error message - incorrect password for given username
            String msg = "Incorrect password for the given username";
            JOptionPane.showMessageDialog(null, msg);
            // clearing pw field
            pwStudentLoginField.setText(null);
        } else {
            tutee = loginPanel1.tutees.get(loginPanel1.exist());
            // play login sound effect
            soundEffect("login.wav");
            try {
                // navigate to student welcome page, close login
                studentWelcomeFrame = new StudentWelcomeFrame();
                studentWelcomeFrame.welcomeLabel.setText("Welcome, " + tutee.fullName + "!"); 
            } catch (FileNotFoundException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(false);
            studentWelcomeFrame.setVisible(true);
        }
    }//GEN-LAST:event_studentLoginButtonActionPerformed
    /**
     * Plays sound effect for login buttons
     * @param s - audio file name
     */
    public void soundEffect (String s) {
        InputStream sound;
        try {
            //finds the file with a name matching String s
            sound = new FileInputStream(new File(s));
            //intializes audiostream object to play audio
            AudioStream audio = new AudioStream(sound);
            //plays the audio
            AudioPlayer.player.start(audio);
        } catch (IOException e) {
            String msg = "A necessary file is missing.";
            JOptionPane.showMessageDialog(null, msg);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new LoginFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JLabel adminLoginLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loginLabel;
    private peertutormangament.LoginPanel loginPanel1;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JTextField pwAdminLoginField;
    private javax.swing.JLabel pwAdminLoginLabel;
    private javax.swing.JTextField pwStudentLoginField;
    private javax.swing.JLabel pwStudentLoginLabel;
    private javax.swing.JButton studentLoginButton;
    private javax.swing.JLabel studentLoginLabel;
    private javax.swing.JTextField userAdminLoginField;
    private javax.swing.JLabel userAdminLoginLabel;
    private javax.swing.JTextField userStudentLoginField;
    private javax.swing.JLabel userStudentLoginLabel;
    // End of variables declaration//GEN-END:variables
}
