/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peertutormangament;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author claire
 */
public class ResourcesFrame extends javax.swing.JFrame {
    StudentWelcomeFrame studentWelcomeFrame;
    /**
     * Creates new form ResourcesFrame
     * @throws java.io.FileNotFoundException
     */
    public ResourcesFrame() throws FileNotFoundException {
        initComponents();
        studentWelcomeFrame = new StudentWelcomeFrame();
        setTitle("Resources");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resourcesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resourceDataArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resourcesExtArea = new javax.swing.JTextArea();
        resourcesBackButton = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resourcesLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        resourcesLabel.setText("Resources");
        getContentPane().add(resourcesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        resourceDataArea.setEditable(false);
        resourceDataArea.setColumns(20);
        resourceDataArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        resourceDataArea.setRows(5);
        resourceDataArea.setText("https://pubmed.ncbi.nlm.nih.gov/ \nhttps://scholar.google.com/\nhttps://sciencing.com/\nhttps://www.britannica.com/\nhttps://www.scopus.com/\nhttps://link.gale.com/\nhttps://www.jstor.org/\n\nCitations: \nhttps://www.scribbr.com/ ");
        jScrollPane1.setViewportView(resourceDataArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 123, 671, 162));

        resourcesExtArea.setEditable(false);
        resourcesExtArea.setColumns(20);
        resourcesExtArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        resourcesExtArea.setRows(5);
        resourcesExtArea.setText("Kami - an annotation tool that you or your teachers may use to digitally mark \nassessments\nEquatio - turns written math formulas into photos you can insert in documents\nGrammarly - checks your grammar, spelling, and word choice\nNod - emoji reactions in Google Meets");
        jScrollPane2.setViewportView(resourcesExtArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 332, 671, 171));

        resourcesBackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resourcesBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peertutormangament/back.png"))); // NOI18N
        resourcesBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resourcesBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 85, 36));

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label1.setText("Databases and research sites:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label2.setText("Chrome extensions:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peertutormangament/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resourcesBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesBackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        studentWelcomeFrame.welcomeLabel.setText("I hope that was useful");
        studentWelcomeFrame.setVisible(true);
    }//GEN-LAST:event_resourcesBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourcesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourcesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourcesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourcesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new ResourcesFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ResourcesFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextArea resourceDataArea;
    private javax.swing.JButton resourcesBackButton;
    private javax.swing.JTextArea resourcesExtArea;
    private javax.swing.JLabel resourcesLabel;
    // End of variables declaration//GEN-END:variables
}
