/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peertutormangament;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Student Welcome Frame
 * @author claire
 */
public class StudentWelcomeFrame extends javax.swing.JFrame {
    // init navigation 
    BookSearchFrame bookSearchFrame;
    ResourcesFrame resourcesFrame;
    SupportFrame supportFrame;
    LoginFrame loginFrame;
    /**
     * Creates new form StudentWelcomeFrame
     * @throws java.io.FileNotFoundException
     */
    public StudentWelcomeFrame() throws FileNotFoundException {
        initComponents();
        setTitle("Welcome!");
    }
    
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookButton = new javax.swing.JButton();
        resourcesButton = new javax.swing.JButton();
        supportButton = new javax.swing.JButton();
        welcomeLabel = new java.awt.Label();
        logOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookButton.setText("Book a tutor");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 147, 44));

        resourcesButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resourcesButton.setText("Resources");
        resourcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resourcesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 147, 44));

        supportButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supportButton.setText("Support");
        supportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 147, 44));

        welcomeLabel.setAlignment(java.awt.Label.CENTER);
        welcomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 42)); // NOI18N
        welcomeLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                welcomeLabelComponentShown(evt);
            }
        });
        getContentPane().add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 780, -1));

        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peertutormangament/logout.png"))); // NOI18N
        logOutButton.setText("Logout");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peertutormangament/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // navigating to book frame
        bookSearchFrame = new BookSearchFrame();
        setVisible(false);
        bookSearchFrame.setVisible(true);
    }//GEN-LAST:event_bookButtonActionPerformed

    private void resourcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesButtonActionPerformed
        try {
            // navigating to resources
            resourcesFrame = new ResourcesFrame();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StudentWelcomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        resourcesFrame.setVisible(true);
    }//GEN-LAST:event_resourcesButtonActionPerformed

    private void supportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportButtonActionPerformed
        // navigating to support
        supportFrame = new SupportFrame();
        setVisible(false);
        supportFrame.setVisible(true);
    }//GEN-LAST:event_supportButtonActionPerformed

    private void welcomeLabelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_welcomeLabelComponentShown

    }//GEN-LAST:event_welcomeLabelComponentShown

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        try {
            // TODO add your handling code here:
            loginFrame = new LoginFrame();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StudentWelcomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        loginFrame.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentWelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentWelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentWelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentWelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new StudentWelcomeFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(StudentWelcomeFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton resourcesButton;
    private javax.swing.JButton supportButton;
    public java.awt.Label welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
